### ISSUE TITLE
5주차 프로그래머스

### ISSUE THREAD

**Issue by ayuriK152** [DoYouKnow-Algorithm/2023AutumnSeason#15]
12918 문자열 다루기 기본
https://school.programmers.co.kr/learn/courses/30/lessons/12918

12915 문자열 내 마음대로 정렬하기
https://school.programmers.co.kr/learn/courses/30/lessons/12915

81301 숫자 문자열과 영단어
https://school.programmers.co.kr/learn/courses/30/lessons/81301

**Comment by rvbear** [comment]
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/107176570/fc0f6a35-d677-4cbe-88b4-dcb6e1647ce7)
12918 해결!

**Comment by Hj1218** [comment]
12918 문자열 다루기 기본
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/114800998/cc2daa18-e8b7-46a0-a6ec-3536b121a9b1)

**Comment by rvbear** [comment]
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/107176570/8a10a0a4-bcd1-48a4-b380-d2d5778adfae)
12915 해결!

**Comment by Hj1218** [comment]
12915 문자열 내 마음대로 정렬하기
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/114800998/1bec649e-a0f1-47d0-b186-2b8a7302bcc6)

**Comment by rvbear** [comment]
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/107176570/40830e18-511c-4a77-a8d6-f49a93a2942f)
81301 해결!

**Comment by jihye1006** [comment]
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/87265951/b823df8b-549e-4793-a9ed-d0c6281fffed)

<12918 해결>

**Comment by jihye1006** [comment]
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/87265951/1459ca3a-312c-42e8-99db-4e8c7a29163a)

<12915 해결>

**Comment by sunjae98** [comment]
<img width="691" alt="스크린샷 2023-11-05 오후 10 09 08" src="https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/83015089/4e0de8a1-3319-4d06-ab94-bf90c1003699">

12918 문자열 다루기 기본

**Comment by Hj1218** [comment]
81301 숫자 문자열과 영단어
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/114800998/3f9c0ccc-f6d5-4148-be30-3a8f43d418ef)

**Comment by heedong12** [comment]
<img width="358" alt="image" src="https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/114553010/3b140974-4323-415a-ae0d-9e724fcbe830">

12918 해결
난 특별하게 이거 캡쳐해서 올릴랭ㅎ.ㅎ

**Comment by jihye1006** [comment]
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/87265951/8e5b3e6e-18fe-4611-a4de-110d431ca5d9)

<81301 해결>

**Comment by heedong12** [comment]
<img width="534" alt="image" src="https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/114553010/52173715-926d-45c7-8ccf-b1c74ec8a2fb">
12915 해결

**Comment by sunjae98** [comment]
<img width="1040" alt="스크린샷 2023-11-07 오후 11 28 51" src="https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/83015089/494b7945-e336-441a-bb6e-c125e63fce37">
12915 문자열 내 마음대로 정렬하기

**Comment by heedong12** [comment]
<img width="360" alt="image" src="https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/114553010/eb0af81b-a37f-40c2-bd44-ef15c2eeb8a4">
81301 해결

**Comment by ayuriK152** [comment]
12918
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/77537017/baedd8a8-2816-43f1-bc0e-885dc5d31fee)

**Comment by ayuriK152** [comment]
12915
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/77537017/708f4afd-1eea-4eb0-b2a8-dd511f40e0c5)

**Comment by ayuriK152** [comment]
81301
![image](https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/77537017/db6c5538-2e9c-45af-a6ef-47371b12f1e0)

**Comment by sunjae98** [comment]
<img width="982" alt="스크린샷 2023-11-08 오전 1 46 11" src="https://github.com/DoYouKnow-Algorithm/2023AutumnSeason/assets/83015089/13050d91-a8ff-44d6-bb9d-06966e6e3a8f">
81301 숫자 문자열과 영단어
